

# Import Libary
# 

In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import os


# Setup Dataset from kaggle

In [2]:
os.listdir('/kaggle/input')

['btc-price']

In [4]:
df = pd.read_csv('dt.csv')

In [5]:
df.head()

nim                  nama  ips1  ips2  ips3  ips4  ips5  ips6  ips7  \
0  15090032         GAGAS PRASTYA  3.00  0.00  0.00  3.90  3.87  4.00  0.00   
1  15090033            AHMAD YANI  2.14  0.65  0.00  0.00  0.00  0.00  0.00   
2  15090034  ALFAN FAIZAL ARSIDIN  3.24  3.25  3.26  3.50  3.33  3.48  3.58   
3  15090035       RIO ADI SUGANDA  0.00  0.00  0.00  0.00  0.00  0.00  0.00   
4  15090036  INDRI NOVI RAHMAWATI  3.33  3.20  3.17  3.14  3.48  3.52  3.58   

   ips8   ipk  
0  0.00  1.85  
1  0.00  0.35  
2  3.25  3.36  
3  0.00  0.00  
4  3.25  3.33

# takes column variable x (price_open, price_high, price_low) and takes colom variable y (price_close)


In [5]:
x = df.iloc[:, 0:3].values 
y = df.iloc[:, -1].values 
print(x)
print(y)

[[  732.      757.99    729.01 ]
 [  750.76    798.7     742.5  ]
 [  784.19    818.99    767.62 ]
 ...
 [47542.2   48160.    46078.327]
 [46471.24  47949.3   45926.   ]
 [47122.09  48604.75  45530.3  ]]
[  754.9    784.19   809.4  ... 46471.24 47122.08 46211.24]


In [8]:
x = df.drop(labels=['nim','nama','ipk'], axis=1).values
y = df['ipk'].values


# Setup train and test

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0) #membagi dataset menjadi data training dan testing

# Create Model

In [10]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

# Make predictions


In [11]:
y_pred = regressor.predict(x_test)
print(y_pred)

[3.20133033e+00 3.29058792e+00 3.23049196e+00 4.08055052e-02
 3.59274005e+00 3.65026107e+00 8.55869304e-01 3.02787607e+00
 2.56143441e+00 3.58912138e+00 2.57330671e+00 3.24943104e+00
 3.47780677e+00 3.06528834e+00 3.31653409e+00 7.80689752e-04
 9.98550775e-01 2.98800150e+00 3.41008169e+00 3.24496949e+00
 3.70281972e+00 9.03380104e-01 2.90541858e+00 3.67411739e+00
 3.13509085e+00 3.10045884e+00 3.98277706e+00 8.92284710e-01
 3.56787078e+00 3.45297328e+00 3.81285698e+00 3.37376206e+00
 2.97903878e+00 9.33380755e-02 3.55404164e+00 3.62773682e+00
 6.23337074e-01 3.08272613e+00 3.32160250e+00 3.50027888e+00
 3.34737744e-01 2.81254527e+00 7.09833350e-01 2.96651192e+00
 3.25179790e+00 2.96018844e+00 2.86780589e+00 3.20530834e+00
 3.42921446e+00 2.25303310e+00 3.32307392e+00 3.40022701e+00
 3.23409697e+00 3.28280520e+00 2.84297373e+00 3.49666154e-01
 7.80689752e-04 3.60929032e+00 3.49531531e+00 3.04782073e+00
 2.62162757e+00 3.09529453e+00 3.12060750e+00 3.74169053e+00
 3.29533650e+00 2.824145

# Mean Absolute Percentage error

In [12]:
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(y_test, y_pred)
print('MAPE : %f' % mape)

MAPE : 101420598367.617096


# Test Score

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9999921917996453

# Show value Coef and Intercept

In [14]:
b = regressor.coef_ #menampilkan konstanta (nilai b)
a = regressor.intercept_ #menampilkan nilai intercept (nilai a)
print(a)
print(b)

0.0007806897521209777
[0.12507755 0.12495309 0.12507264 0.12473587 0.12545725 0.12463533
 0.12493604 0.12500903]


# Testing Prediction Btc Price

In [15]:
regressor.predict([[ 2.19, 3.12, 3.26, 2.92, 3.9, 2.92, 3.11, 3.12]])

array([3.06831743])

# Save Model to Pickle

In [13]:
import pickle
pickle.dump(regressor,open('model.pkl', 'wb'))